package squad;

public enum Attr
{
	CORNERS, CROSSING, DRIBBLING, FINISHING, FIRST_TOUCH, FREE_KICK_TAKING,
	HEADING, LONG_SHOTS, LONG_THROWS, MARKING, PASSING, PENALTY_TAKING,
	TACKLING, TECHNIQUE, AGGRESSION, ANTICIPATION, BRAVERY, COMPOSURE,
	CONCENTRATION, DECISIONS, DETERMINATION, FLAIR, LEADERSHIP, OFF_THE_BALL,
	POSITIONING, TEAMWORK, VISION, WORK_RATE, ACCELERATION, AGILITY,
	BALANCE, JUMPING_REACH, NATURAL_FITNESS, PACE, STAMINA, STRENGTH,
	AERIAL_REACH, COMMAND_OF_AREA, COMMUNICATION, ECCENTRICITY, HANDLING,
	KICKING, ONE_VS_ONES, PUNCHING_TENDENCY, REFLEXES, RUSHING_OUT_TENDENCY, THROWING
}
